version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:80